---
- include: playbooks/pxeboot-servers.yml
- include: playbooks/wait-for-ssh.yml

- name: add ssh fingerprints to deployment host
  hosts: deployer
  tasks:
  - name:
    shell: |
      for i in $(cat /opt/osic-ref-impl/playbooks/inventory/static-inventory.yml | awk /ansible_ssh_host/ | cut -d'=' -f2); do
        ssh-keygen -R $i
        ssh-keyscan -H $i >> /root/.ssh/known_hosts
      done
