---
# 502 - MANAGEMENT_NET - 172.24.8.0/22
# 530 - STORAGE_NET    - 172.24.100.0/22
# 531 - OVERLAY_NET    - 172.24.104.0/22
# 532 - FLAT_NET       - 172.24.108.0/22

# /etc/openstack_deploy/openstack_user_config.yml
cidr_networks:
  container: 172.24.8.0/22
  storage: 172.24.100.0/22
  tunnel: 172.24.104.0/22

used_ips:
  - 172.24.8.1,172.24.9.254
  - 172.24.100.1,172.24.101.254
  - 172.24.104.1,172.24.105.254
  - 172.24.108.1,172.24.109.254

global_overrides:
  internal_lb_vip_address: "172.24.9.253"
  external_lb_vip_address: "172.24.109.253"
  management_bridge: "br-mgmt"
  tunnel_bridge: "br-vxlan"
  provider_networks:
    - network:
        group_binds:
          - all_containers
          - hosts
        type: "raw"
        container_bridge: "br-mgmt"
        container_interface: "eth1"
        container_type: "veth"
        ip_from_q: "container"
        is_container_address: true
        is_ssh_address: true
    - network:
        group_binds:
          - glance_api
          - cinder_api
          - cinder_volume
          - nova_compute
          # Uncomment the next line if using ceph
          # - mons
          # Uncomment the next line if using swift with a storage network.
          - swift_proxy
        type: "raw"
        container_bridge: "br-storage"
        container_type: "veth"
        container_interface: "eth2"
        container_mtu: "9000"
        ip_from_q: "storage"
    - network:
        group_binds:
          - neutron_linuxbridge_agent
        container_bridge: "br-vxlan"
        container_type: "veth"
        container_interface: "eth10"
        container_mtu: "9000"
        ip_from_q: "tunnel"
        type: "vxlan"
        range: "5000:50000"
        net_name: "vxlan"
    - network:
        group_binds:
          - neutron_linuxbridge_agent
        container_bridge: "br-vlan"
        container_type: "veth"
        container_interface: "eth11"
        type: "vlan"
        range: "539:549"
        net_name: "vlan"
    - network:
        group_binds:
          - neutron_linuxbridge_agent
        container_bridge: "br-vlan"
        container_type: "veth"
        container_interface: "eth12"
        host_bind_override: "bond0.532"
        type: "flat"
        net_name: "flat"

shared-infra_hosts:
  infra01:
    ip: 172.24.8.23
  infra02:
    ip: 172.24.8.24
  infra03:
    ip: 172.24.8.25

repo-infra_hosts:
  infra01:
    ip: 172.24.8.23
  infra02:
    ip: 172.24.8.24
  infra03:
    ip: 172.24.8.25

os-infra_hosts:
  infra01:
    ip: 172.24.8.23
  infra02:
    ip: 172.24.8.24
  infra03:
    ip: 172.24.8.25
