---
- name: update the kernel
  hosts: all:!deployer:!provisioner
  tasks:
  - name: update cache
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: update the kernel
    apt:
      name: linux-generic-lts-xenial
      state: present
